# Generated by Django 3.0.5 on 2020-04-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkOrderEscalation', '0002_auto_20200416_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderescalation',
            name='AssignedTeamEmail',
            field=models.CharField(default='gurdaan.walia7@gmail.com', max_length=200),
        ),
    ]
